DROP TABLE SALES_FACT;
DROP TABLE CUSTOMER_D;
DROP TABLE STORE_D;
DROP TABLE SUPPLIER_D;
DROP TABLE PRODUCT_D;
DROP TABLE TIME_D;

CREATE TABLE "STORE_D"(
  "STORE_ID" VARCHAR2(4), 
  "STORE_NAME" VARCHAR2(20),
  CONSTRAINT STORE_ID_PKID PRIMARY KEY (STORE_ID)
);

CREATE TABLE "SUPPLIER_D"(
  "SUPPLIER_ID" VARCHAR2(5), 
  "SUPPLIER_NAME" VARCHAR2(30),
  CONSTRAINT SUPPLIER_ID_PKID PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE "PRODUCT_D"(
  "PRODUCT_ID" VARCHAR2(6),
  "PRODUCT_NAME" VARCHAR2(30),
  "PRICE" NUMBER(5,2),
  CONSTRAINT PRODUCT_ID_PKID PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE "CUSTOMER_D"(
  "CUSTOMER_ID" VARCHAR2(4),
  "CUSTOMER_NAME" VARCHAR2(30),
  CONSTRAINT CUSTOMER_ID_PKID PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE "TIME_D"(
  TIME_ID DATE,  
  DATE_YEAR_CODE NUMBER,
  DAY_CODE VARCHAR2(30),
  WEEK_CODE NUMBER,
  MONTH_CODE NUMBER,
  QUARTER_CODE NUMBER,
  YEAR_CODE NUMBER,
  CONSTRAINT TIME_ID_PKID PRIMARY KEY (TIME_ID)
);

CREATE TABLE "SALES_FACT"(
  "STORE_ID" VARCHAR2(5), 
  "SUPPLIER_ID" VARCHAR2(5),
  "PRODUCT_ID" VARCHAR2(6),
  "CUSTOMER_ID" VARCHAR2(4),
  "T_DATE" DATE,
  "QUANTITY" NUMBER(3,0),
  "SALES" NUMBER(5,2),
  CONSTRAINT FACT_STORE_ID_FKID FOREIGN KEY (STORE_ID) REFERENCES STORE_D(STORE_ID),
  CONSTRAINT FACT_SUPPLIER_ID_FKID FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER_D (SUPPLIER_ID),
  CONSTRAINT FACT_PRODUCT_ID_FKID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_D (PRODUCT_ID),
  CONSTRAINT FACT_CUSTOMER_ID_FKID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_D (CUSTOMER_ID),
  CONSTRAINT FACT_TIME_ID_FKID FOREIGN KEY (T_DATE) REFERENCES TIME_D(TIME_ID)
);
